# -*- coding: utf-8 -*-
"""Zinc light and dark design tokens."""

DARK_TOKENS = {
    'bg_primary': '#09090b',
    'bg_surface': '#18181b',
    'bg_input': '#09090b',
    'bg_input_disabled': '#18181b',
    'bg_sidebar': '#09090b',
    'text_primary': '#fafafa',
    'text_secondary': '#a1a1aa',
    'text_disabled': '#71717a',
    'text_highlight': '#fafafa',
    'border_color': '#27272a',
    'border_disabled': '#18181b',
    'accent': '#fafafa',
    'accent_hover': '#e4e4e7',
    'accent_pressed': '#fafafa',
    'selection_bg': '#27272a',
    'selection_text': '#fafafa',
    'btn_primary_bg': '#fafafa',
    'btn_primary_text': '#18181b',
    'btn_primary_hover': '#e4e4e7',
    'btn_primary_pressed': '#fafafa',
    'btn_success_bg': '#22c55e',
    'btn_success_text': '#09090b',
    'btn_success_hover': '#4ade80',
    'btn_success_pressed': '#22c55e',
    'btn_danger_bg': '#ef4444',
    'btn_danger_text': '#fafafa',
    'btn_danger_hover': '#f87171',
    'btn_danger_pressed': '#ef4444',
    'btn_secondary_bg': '#18181b',
    'btn_secondary_text': '#fafafa',
    'btn_secondary_hover': '#27272a',
    'btn_secondary_pressed': '#09090b',
    'btn_secondary_border': '#27272a',
    'sidebar_selected_bg': '#27272a',
    'sidebar_selected_text': '#fafafa',
    'scrollbar_bg': '#09090b',
    'scrollbar_handle': '#27272a',
    'scrollbar_handle_hover': '#3f3f46',
    'combo_popup_selected_bg': '#27272a',
    'combo_popup_selected_text': '#fafafa',
    'table_grid': '#27272a',
    'spin_arrow_fill': '%23fafafa',
    'spin_arrow_fill_disabled': '%2371717a',
    'checkbox_checked_bg': '#fafafa',
    'checkbox_checked_border': '#fafafa',
    'checkbox_check_color': '%2318181b',
}

LIGHT_TOKENS = {
    'bg_primary': '#fafafa',
    'bg_surface': '#ffffff',
    'bg_input': '#ffffff',
    'bg_input_disabled': '#f4f4f5',
    'bg_sidebar': '#fafafa',
    'text_primary': '#09090b',
    'text_secondary': '#71717a',
    'text_disabled': '#a1a1aa',
    'text_highlight': '#09090b',
    'border_color': '#e4e4e7',
    'border_disabled': '#fafafa',
    'accent': '#18181b',
    'accent_hover': '#27272a',
    'accent_pressed': '#09090b',
    'selection_bg': '#f4f4f5',
    'selection_text': '#09090b',
    'btn_primary_bg': '#18181b',
    'btn_primary_text': '#ffffff',
    'btn_primary_hover': '#27272a',
    'btn_primary_pressed': '#09090b',
    'btn_success_bg': '#16a34a',
    'btn_success_text': '#ffffff',
    'btn_success_hover': '#15803d',
    'btn_success_pressed': '#166534',
    'btn_danger_bg': '#dc2626',
    'btn_danger_text': '#ffffff',
    'btn_danger_hover': '#b91c1c',
    'btn_danger_pressed': '#991b1b',
    'btn_secondary_bg': '#ffffff',
    'btn_secondary_text': '#18181b',
    'btn_secondary_hover': '#f4f4f5',
    'btn_secondary_pressed': '#e4e4e7',
    'btn_secondary_border': '#e4e4e7',
    'sidebar_selected_bg': '#f4f4f5',
    'sidebar_selected_text': '#09090b',
    'scrollbar_bg': '#fafafa',
    'scrollbar_handle': '#e4e4e7',
    'scrollbar_handle_hover': '#d4d4d8',
    'combo_popup_selected_bg': '#f4f4f5',
    'combo_popup_selected_text': '#09090b',
    'table_grid': '#f4f4f5',
    'spin_arrow_fill': '%2318181b',
    'spin_arrow_fill_disabled': '%23a1a1aa',
    'checkbox_checked_bg': '#18181b',
    'checkbox_checked_border': '#18181b',
    'checkbox_check_color': '%23ffffff',
}


