"""Legacy Vietnamese font lookup tables."""

# ═══════════════════════════════════════════════════════════════
# BẢNG ÁNH XẠ TCVN3 (ABC) ↔ UNICODE
# ═══════════════════════════════════════════════════════════════
_UNICODE_FULL = [
    'À', 'Á', 'Â', 'Ã', 'È', 'É', 'Ê', 'Ì', 'Í', 'Ò',
    'Ó', 'Ô', 'Õ', 'Ù', 'Ú', 'Ý', 'à', 'á', 'â', 'ã',
    'è', 'é', 'ê', 'ì', 'í', 'ò', 'ó', 'ô', 'õ', 'ù',
    'ú', 'ý', 'Ă', 'ă', 'Đ', 'đ', 'Ĩ', 'ĩ', 'Ũ', 'ũ',
    'Ơ', 'ơ', 'Ư', 'ư', 'Ạ', 'ạ', 'Ả', 'ả', 'Ấ', 'ấ',
    'Ầ', 'ầ', 'Ẩ', 'ẩ', 'Ẫ', 'ẫ', 'Ậ', 'ậ', 'Ắ', 'ắ',
    'Ằ', 'ằ', 'Ẳ', 'ẳ', 'Ẵ', 'ẵ', 'Ặ', 'ặ', 'Ẹ', 'ẹ',
    'Ẻ', 'ẻ', 'Ẽ', 'ẽ', 'Ế', 'ế', 'Ề', 'ề', 'Ể', 'ể',
    'Ễ', 'ễ', 'Ệ', 'ệ', 'Ỉ', 'ỉ', 'Ị', 'ị', 'Ọ', 'ọ',
    'Ỏ', 'ỏ', 'Ố', 'ố', 'Ồ', 'ồ', 'Ổ', 'ổ', 'Ỗ', 'ỗ',
    'Ộ', 'ộ', 'Ớ', 'ớ', 'Ờ', 'ờ', 'Ở', 'ở', 'Ỡ', 'ỡ',
    'Ợ', 'ợ', 'Ụ', 'ụ', 'Ủ', 'ủ', 'Ứ', 'ứ', 'Ừ', 'ừ',
    'Ử', 'ử', 'Ữ', 'ữ', 'Ự', 'ự', 'Ỳ', 'ỳ', 'Ỵ', 'ỵ',
    'Ỷ', 'ỷ', 'Ỹ', 'ỹ',
]

_TCVN3_FULL = [
    'A\xb5',
    'A\xb8',
    '\xa2',
    'A\xb7',
    'E\xcc',
    'E\xd0',
    '\xa3',
    'I\xd7',
    'I\xdd',
    'O\xdf',
    'O\xe3',
    '\xa4',
    'O\xe2',
    'U\xef',
    'U\xf3',
    'Y\xfd',
    '\xb5',
    '\xb8',
    '\xa9',
    '\xb7',
    '\xcc',
    '\xd0',
    '\xaa',
    '\xd7',
    '\xdd',
    '\xdf',
    '\xe3',
    '\xab',
    '\xe2',
    '\xef',
    '\xf3',
    '\xfd',
    '\xa1',
    '\xa8',
    '\xa7',
    '\xae',
    'I\xdc',
    '\xdc',
    'U\xf2',
    '\xf2',
    '\xa5',
    '\xac',
    '\xa6',
    '\xad',
    'A\xb9',
    '\xb9',
    'A\xb6',
    '\xb6',
    '\xa2\xca',
    '\xca',
    '\xa2\xc7',
    '\xc7',
    '\xa2\xc8',
    '\xc8',
    '\xa2\xc9',
    '\xc9',
    '\xa2\xcb',
    '\xcb',
    '\xa1\xbe',
    '\xbe',
    '\xa1\xbb',
    '\xbb',
    '\xa1\xbc',
    '\xbc',
    '\xa1\xbd',
    '\xbd',
    '\xa1\xc6',
    '\xc6',
    'E\xd1',
    '\xd1',
    'E\xce',
    '\xce',
    'E\xcf',
    '\xcf',
    '\xa3\xd5',
    '\xd5',
    '\xa3\xd2',
    '\xd2',
    '\xa3\xd3',
    '\xd3',
    '\xa3\xd4',
    '\xd4',
    '\xa3\xd6',
    '\xd6',
    'I\xd8',
    '\xd8',
    'I\xde',
    '\xde',
    'O\xe4',
    '\xe4',
    'O\xe1',
    '\xe1',
    '\xa4\xe8',
    '\xe8',
    '\xa4\xe5',
    '\xe5',
    '\xa4\xe6',
    '\xe6',
    '\xa4\xe7',
    '\xe7',
    '\xa4\xe9',
    '\xe9',
    '\xa5\xed',
    '\xed',
    '\xa5\xea',
    '\xea',
    '\xa5\xeb',
    '\xeb',
    '\xa5\xec',
    '\xec',
    '\xa5\xee',
    '\xee',
    'U\xf4',
    '\xf4',
    'U\xf1',
    '\xf1',
    '\xa6\xf8',
    '\xf8',
    '\xa6\xf5',
    '\xf5',
    '\xa6\xf6',
    '\xf6',
    '\xa6\xf7',
    '\xf7',
    '\xa6\xf9',
    '\xf9',
    'Y\xfa',
    '\xfa',
    'Y\xfe',
    '\xfe',
    'Y\xfb',
    '\xfb',
    'Y\xfc',
    '\xfc',
]

# Tạo các từ điển tra cứu nhanh
_UNI2TCVN = {}
_TCVN2UNI_1 = {}   # Ký tự TCVN3 1 byte → Unicode
_TCVN2UNI_2 = {}   # Chuỗi TCVN3 2 byte → Unicode

for _i in range(len(_UNICODE_FULL)):
    _u = _UNICODE_FULL[_i]
    _t = _TCVN3_FULL[_i]
    _UNI2TCVN[_u] = _t
    if len(_t) == 2:
        _TCVN2UNI_2[_t] = _u
    else:
        _TCVN2UNI_1[_t] = _u


