# -*- coding: utf-8 -*-
"""Runtime helpers for generated cadastral layers."""

from __future__ import annotations


PLUGIN_PROP = "vnu2f_qlddk68/generated"
SOURCE_PROP = "vnu2f_qlddk68/source"
KIND_PROP = "vnu2f_qlddk68/kind"


def remove_previous_generated_layers(
    project,
    source_key: str,
    kinds: tuple[str, ...],
    legacy_names: tuple[str, ...] = (),
) -> int:
    """Remove earlier layers generated by this importer for the same source."""
    removed = 0
    if not project or not source_key:
        return removed

    for layer_id, layer in list(project.mapLayers().items()):
        try:
            is_generated = bool(layer.customProperty(PLUGIN_PROP, False))
            same_source = layer.customProperty(SOURCE_PROP, "") == source_key
            same_kind = layer.customProperty(KIND_PROP, "") in kinds
        except Exception:  # noqa: BLE001 — intentional suppress
            continue
        legacy_match = layer.name() in legacy_names
        if (is_generated and same_source and same_kind) or legacy_match:
            project.removeMapLayer(layer_id)
            removed += 1
    return removed


def prepare_generated_layer(layer, source_key: str, kind: str, feature_count: int = 0) -> None:
    """Tag and tune generated layers so QGIS redraws them more cheaply."""
    try:
        layer.setCustomProperty(PLUGIN_PROP, True)
        layer.setCustomProperty(SOURCE_PROP, source_key)
        layer.setCustomProperty(KIND_PROP, kind)
    except Exception:  # noqa: BLE001 — intentional suppress
        pass

    if feature_count > 250:
        _enable_render_simplification(layer)


def add_generated_layer(project, layer, source_key: str, kind: str, feature_count: int = 0) -> None:
    """Finalize a generated memory layer and add it to the QGIS project."""
    provider = layer.dataProvider()
    try:
        provider.createSpatialIndex()
    except Exception:  # noqa: BLE001 — intentional suppress
        pass
    layer.updateExtents()
    prepare_generated_layer(layer, source_key, kind, feature_count)
    project.addMapLayer(layer)


def _enable_render_simplification(layer) -> None:
    try:
        from qgis.core import QgsVectorSimplifyMethod
    except Exception:  # noqa: BLE001 — intentional suppress
        return

    try:
        method = QgsVectorSimplifyMethod()
        hints = 0
        for name in ("GeometrySimplification", "SimplifyGeometry", "SimplifyEnvelope"):
            value = getattr(QgsVectorSimplifyMethod, name, None)
            if value is not None:
                hints |= int(value)
        if hints:
            method.setSimplifyHints(hints)

        algorithm = getattr(QgsVectorSimplifyMethod, "Distance", None)
        if algorithm is not None and hasattr(method, "setSimplifyAlgorithm"):
            method.setSimplifyAlgorithm(algorithm)

        if hasattr(method, "setThreshold"):
            method.setThreshold(1.0)
        elif hasattr(method, "setTolerance"):
            method.setTolerance(0.05)

        if hasattr(method, "setForceLocalOptimization"):
            method.setForceLocalOptimization(True)
        if hasattr(layer, "setSimplifyMethod"):
            layer.setSimplifyMethod(method)
    except Exception:  # noqa: BLE001 — intentional suppress
        pass
